### ISSUE TITLE
Triple tick code block ```hbs should work in this addon, per ember-prism fix

### ISSUE THREAD

**Issue by amyrlam** [empress/ember-showdown-prism#17]
Functionality was introduced in: https://github.com/shipshapecode/ember-prism/pull/279, if hifi-glimmer is enabled, hbs works fine

See conversation on:  https://github.com/ember-learn/ember-blog/pull/1010

**Comment by amyrlam** [comment]
ember-prism is out of date, could just be that: https://github.com/empress/ember-showdown-prism/blob/master/package.json#L34

**Comment by mansona** [comment]
in #45 I removed ember-prism from this as a dependency because actually we're relying on global Prism (and always have been) so having prism as a dependency doesn't make sense.

I guess it should be a peer-dependency but really it should be done slightly differently 🙈 I'm closing this because if you want a newer ember-prism you update it in your app 👍
